-- Product archive for the Admin → Restore Products page.
-- Run this once in the Supabase SQL Editor (Dashboard → SQL Editor → New Query) before using the archive/restore workflow.

create table if not exists public.deleted_products (
  id bigint generated by default as identity primary key,
  original_product_id bigint,
  product_data jsonb not null,
  deleted_at timestamptz not null default now()
);

create index if not exists deleted_products_deleted_at_idx
  on public.deleted_products (deleted_at desc);

-- Disable Row Level Security so admin restore/delete operations work seamlessly
alter table public.deleted_products disable row level security;
